#include "Exception.hpp"
#include "Print.hpp"

#include <cmath>

namespace Slic3r {

namespace {

bool internal_solid_infill_uses_sparse_filament(const PrintRegionConfig &config, FlowRole role)
{
    return role == frSolidInfill && std::abs(config.sparse_infill_density.value - 100.) < EPSILON;
}

} // namespace

// See the declaration in Print.hpp. Extracted from GCode::process_layer's
// `configured_filament_id_1based` / `configured_extruder_id` lambdas, which each carried their own
// copy of this rule.
//
// WAVE A / item 9 (.superpowers/sdd/2026-08-31-paint-depth/classic-generator-investigation.md
// section 0, "The one configuration where it IS a real defect"): GAP FILL FOLLOWS THE WALL
// FILAMENT. Gap fill is generated by the perimeter generator as part of the wall stack
// (PerimeterGenerator::process_classic -> gap_fill -> LayerRegion::thin_fills) and is only
// *stored* in the fills collection, which Fill::make_fill() copies it into. Deciding its filament
// from that bucket sent it to sparse_infill_filament, and a painted PrintRegion sets
// wall_filament and solid_infill_filament to the painted extruder unconditionally but
// sparse_infill_filament only when paint_sparse_infill is on (PrintApply.cpp) - so with "Paint
// sparse infill" unchecked, ~37% of an N=3 painted band (the middle gap-fill line, sitting
// directly behind the single painted outer loop) silently printed in the BASE filament, while
// that option's own tooltip promises "walls and solid infill still print in the painted
// filament". process_arachne never calls gap_fill, which is why the defect was classic-only and
// invisible to every Arachne slice this feature was validated against.
//
// The role already says gap fill is not infill (is_infill(erGapFill) is false,
// ExtrusionEntity.hpp), and LayerTools::extruder (GCode/ToolOrdering.cpp) has always routed a
// gap-fill-only collection to wall_filament on exactly that basis - so tool ordering and G-code
// emission used to disagree about which extruder the painted band's gap fill needs. They now
// agree. Only erGapFill is redirected, deliberately: erNone (an empty collection) and any future
// role keep the old fall-through.
FillFilamentSource fill_filament_source(const PrintRegionConfig &config, ExtrusionRole role)
{
    if (role == erGapFill)
        return FillFilamentSource::Wall;
    if (role == erSolidInfill && std::abs(config.sparse_infill_density.value - 100.) < EPSILON)
        return FillFilamentSource::SparseInfill;
    if (is_solid_infill(role))
        return FillFilamentSource::SolidInfill;
    return FillFilamentSource::SparseInfill;
}

// 1-based extruder identifier for this region and role.
unsigned int PrintRegion::extruder(FlowRole role) const
{
    size_t extruder = 0;
    if (role == frExternalPerimeter)
        // Ultra: outer walls may use their own filament (0 = follow walls)
        extruder = m_config.outer_wall_filament.value > 0 ? m_config.outer_wall_filament : m_config.wall_filament;
    else if (role == frPerimeter)
        extruder = m_config.wall_filament;
    else if (role == frInfill)
        extruder = m_config.sparse_infill_filament;
    else if (role == frSolidInfill)
        extruder = internal_solid_infill_uses_sparse_filament(m_config, role) ? m_config.sparse_infill_filament : m_config.solid_infill_filament;
    else if (role == frTopSolidInfill)
        extruder = m_config.solid_infill_filament;
    else
        throw Slic3r::InvalidArgument("Unknown role");
    return extruder;
}

Flow PrintRegion::flow(const PrintObject &object, FlowRole role, double layer_height, bool first_layer) const
{
    const PrintConfig          &print_config = object.print()->config();
    ConfigOptionFloatOrPercent config_width;
    // Get extrusion width from configuration.
    // (might be an absolute value, or a percent value, or zero for auto)
    if (first_layer && print_config.initial_layer_line_width.value > 0) {
        config_width = print_config.initial_layer_line_width;
    } else if (role == frExternalPerimeter) {
        config_width = m_config.outer_wall_line_width;
    } else if (role == frPerimeter) {
        config_width = m_config.inner_wall_line_width;
    } else if (role == frInfill) {
        config_width = m_config.sparse_infill_line_width;
    } else if (role == frSolidInfill) {
        config_width = m_config.internal_solid_infill_line_width;
    } else if (role == frTopSolidInfill) {
        config_width = m_config.top_surface_line_width;
    } else {
        throw Slic3r::InvalidArgument("Unknown role");
    }

    if (config_width.value == 0)
        config_width = object.config().line_width;
    
    // Get the configured nozzle_diameter for the extruder associated to the flow role requested.
    // Here this->extruder(role) - 1 may underflow to MAX_INT, but then the get_at() will follback to zero'th element, so everything is all right.
    auto nozzle_diameter = float(print_config.nozzle_diameter.get_at(this->extruder(role) - 1));
    return Flow::new_from_config_width(role, config_width, nozzle_diameter, float(layer_height));
}

coordf_t PrintRegion::nozzle_dmr_avg(const PrintConfig &print_config) const
{
    return (print_config.nozzle_diameter.get_at(m_config.wall_filament.value    - 1) + 
            print_config.nozzle_diameter.get_at(m_config.sparse_infill_filament.value - 1) +
            print_config.nozzle_diameter.get_at(m_config.solid_infill_filament.value - 1)) / 3.;
}

coordf_t PrintRegion::bridging_height_avg(const PrintConfig &print_config) const
{
    return this->nozzle_dmr_avg(print_config) * sqrt(m_config.bridge_flow.value);
}

void PrintRegion::collect_object_printing_extruders(const PrintConfig &print_config, const PrintRegionConfig &region_config, const bool has_brim, std::vector<unsigned int> &object_extruders)
{
    // These checks reflect the same logic used in the GUI for enabling/disabling extruder selection fields.
    // BBS
    auto num_extruders = (int)print_config.filament_diameter.size();
    auto emplace_extruder = [num_extruders, &object_extruders](int extruder_id) {
    	int i = std::max(0, extruder_id - 1);
        object_extruders.emplace_back((i >= num_extruders) ? 0 : i);
    };
    if (region_config.wall_loops.value > 0 || has_brim) {
    	emplace_extruder(region_config.wall_filament);
        // Ultra: outer walls may use their own filament
        if (region_config.wall_loops.value > 0 && region_config.outer_wall_filament.value > 0)
            emplace_extruder(region_config.outer_wall_filament);
    }
    if (region_config.sparse_infill_density.value > 0)
        emplace_extruder(region_config.sparse_infill_filament);
    if (region_config.top_shell_layers.value > 0 || region_config.bottom_shell_layers.value > 0)
    	emplace_extruder(region_config.solid_infill_filament);
}

void PrintRegion::collect_object_printing_extruders(const Print &print, std::vector<unsigned int> &object_extruders) const
{
    // PrintRegion, if used by some PrintObject, shall have all the extruders set to an existing printer extruder.
    // If not, then there must be something wrong with the Print::apply() function.
#ifndef NDEBUG
    // BBS
    auto num_extruders = int(print.config().filament_diameter.size());
    assert(this->config().wall_filament    <= num_extruders);
    assert(this->config().sparse_infill_filament       <= num_extruders);
    assert(this->config().solid_infill_filament <= num_extruders);
#endif
    collect_object_printing_extruders(print.config(), this->config(), print.has_brim(), object_extruders);
}

}
