#!/usr/bin/env bash
# spike/verify_chameleon.sh
#
# Chameleon Brim + Support Interface Auto-Match — repeatable regression check for:
#   1. Off-mode ("object" brim_filament_source) byte-identity vs the frozen
#      baseline_clean.gcode, AND determinism of two consecutive off-mode slices.
#   2. nearest_wall-mode sanity (exit 0, M620 count within the switch-count
#      guard bound, brim feature present) AND determinism of two consecutive
#      nearest_wall slices.
#   3. (Part 2) Support Interface Auto-Match on the tshape.stl fixture:
#      manual-mode support-region identity vs p2_baseline.gcode (tower off/on),
#      nearest_surface-mode sanity (exit 0, bounded M620 growth, feature-tag
#      presence; tower off/on), and a nearest_surface determinism repeat.
#
# Run from anywhere; the script cd's into its own directory (spike/) first so
# all the relative harness paths below resolve the same way regardless of the
# caller's cwd. Requires a built snapmaker-orca.exe (../build/src/Release/).
#
# Plain bash (Git Bash on Windows is fine) — uses process substitution, so
# `bash verify_chameleon.sh` / `./verify_chameleon.sh`, not `sh verify_chameleon.sh`.

set -u
cd "$(dirname "${BASH_SOURCE[0]}")"

# ---------------------------------------------------------------------------
# Harness fixtures (per spike/FINDINGS.md harness notes)
# ---------------------------------------------------------------------------
EXE="../build/src/Release/snapmaker-orca.exe"
DATADIR="C:/Dev/SnapmakerOrcaSupports/spike/datadir"
MACHINE_PROFILE="../resources/profiles/BBL/machine/Bambu Lab X1 Carbon 0.4 nozzle.json"
FIL_PLA="../resources/profiles/BBL/filament/Bambu PLA Basic @BBL X1C.json"
FIL_PETG="../resources/profiles/BBL/filament/Bambu PETG Basic @BBL X1C.json"
OBJ_OVERRIDES="spike_process_overrides.json"      # implicit brim_filament_source = object
CHA_OVERRIDES="spike_chameleon_overrides.json"    # brim_filament_source = nearest_wall

BASELINE="out/baseline_clean.gcode"
PLATE_OUT="out/plate_1.gcode"   # snapmaker-orca.exe's fixed multi-object-plate output name

OUT_OBJ_1="out/verify_object_1.gcode"
OUT_OBJ_2="out/verify_object_2.gcode"
OUT_CHA_1="out/verify_nearestwall_1.gcode"
OUT_CHA_2="out/verify_nearestwall_2.gcode"

M620_MIN=2
M620_MAX=10

# ---------------------------------------------------------------------------
# Support Interface Auto-Match (Part 2) fixtures
# ---------------------------------------------------------------------------
TSHAPE="tshape.stl"
P2_MANUAL_OVERRIDES="spike_support_overrides.json"    # support_interface_filament_source = manual (default)
P2_NEAREST_OVERRIDES="spike_p2_overrides.json"        # + support_interface_filament_source = nearest_surface
P2_BASELINE="out/p2_baseline.gcode"                   # recorded pre-Task-4 (HEAD a157ac6cf8): manual mode, tower off, single PLA filament

OUT_P2_MAN_OFF="out/p2_manual_off.gcode"
OUT_P2_MAN_ON="out/p2_manual_on.gcode"
OUT_P2_NS_OFF_1="out/p2_nearest_off_1.gcode"
OUT_P2_NS_OFF_2="out/p2_nearest_off_2.gcode"
OUT_P2_NS_ON="out/p2_nearest_on.gcode"

# ---------------------------------------------------------------------------
# Preflight — fail fast with a clear message if the harness itself isn't set up,
# rather than limping through every check reporting confusing FAILs.
# ---------------------------------------------------------------------------
preflight_fail=0
for f in "$EXE" "$MACHINE_PROFILE" "$FIL_PLA" "$FIL_PETG" "$OBJ_OVERRIDES" "$CHA_OVERRIDES" "$BASELINE" cube30.stl cube30b.stl \
         "$TSHAPE" "$P2_MANUAL_OVERRIDES" "$P2_NEAREST_OVERRIDES" "$P2_BASELINE"; do
    if [ ! -f "$f" ]; then
        echo "PREFLIGHT FAIL: missing required file: $f" >&2
        preflight_fail=1
    fi
done
if [ ! -d "$DATADIR" ]; then
    echo "PREFLIGHT FAIL: missing datadir: $DATADIR" >&2
    preflight_fail=1
fi
if [ "$preflight_fail" -ne 0 ]; then
    echo "Aborting: harness prerequisites not met (see above). Build snapmaker-orca.exe and/or check spike/ fixtures." >&2
    exit 2
fi

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
RESULTS=()   # "name|PASS/FAIL|detail"
FAILS=0

record() {
    local name="$1" status="$2" detail="$3"
    RESULTS+=("${name}|${status}|${detail}")
    if [ "$status" != "PASS" ]; then
        FAILS=$((FAILS + 1))
    fi
}

# Strip lines/fields known (and verified, see Task 4 report) to legitimately
# differ run-to-run or mode-to-mode without indicating a real regression:
#   - "; generated by ..." header line (build string + wall-clock timestamp)
#   - lines starting "; at " (defensive; currently folded into the line above,
#     kept as its own filter in case a future build ever splits it out)
#   - "; brim_filament_source = ..." config-dump line (value differs
#     object vs nearest_wall by design, and is entirely absent from the
#     pre-Task-3 baseline_clean.gcode, which predates that config key)
#   - "; support_interface_filament_source = ..." config-dump line (Task 2
#     added this key after baseline_clean.gcode was recorded in Part 1, so
#     every current slice — including plain object-mode ones with support
#     untouched — now dumps one extra CONFIG_BLOCK line baseline_clean.gcode
#     doesn't have; confirmed via Task 4's diff investigation to be the
#     *only* diff for the pre-existing Part 1 object-mode checks, i.e. a
#     stale-normalize gap from Task 2/3, not a Task 4 regression)
#   - the "id:<N> copy 0" suffix on "; printing object ..." / "; stop printing
#     object ..." comments — this per-object numeric id is run-to-run
#     nondeterministic (confirmed by back-to-back identical-command runs in
#     Task 4); everything else on those lines, including the stable
#     "unique label id: NN" companion comment, is left untouched.
normalize() {
    sed -e '/^; generated by/d' \
        -e '/^; at /d' \
        -e '/^; brim_filament_source/d' \
        -e '/^; support_interface_filament_source/d' \
        -e 's/id:[0-9]\+ copy 0/id:X copy 0/' \
        "$1"
}

# byte_identical <fileA> <fileB> -> 0 if identical after normalize, 1 otherwise
byte_identical() {
    diff -q <(normalize "$1") <(normalize "$2") > /dev/null 2>&1
}

# run_slice <overrides_json> <dest_gcode> <log_file>
# Slices the two-cube fixture with the given process-overrides JSON, moving
# the CLI's fixed plate_1.gcode output to a stable per-run name so the next
# run doesn't clobber it. Returns the exe's exit code (or 1 if it exited 0
# but produced no plate_1.gcode).
run_slice() {
    local overrides="$1" dest="$2" logfile="$3"
    rm -f "$PLATE_OUT"
    "$EXE" --datadir "$DATADIR" \
        --load-settings "${MACHINE_PROFILE};${overrides}" \
        --load-filaments "${FIL_PLA};${FIL_PETG}" \
        --slice 0 --outputdir out cube30.stl cube30b.stl \
        > "$logfile" 2>&1
    local rc=$?
    if [ $rc -eq 0 ]; then
        if [ -f "$PLATE_OUT" ]; then
            mv -f "$PLATE_OUT" "$dest"
        else
            rc=1
        fi
    fi
    return $rc
}

# run_slice_p2 <overrides_json> <filaments_semicolon_list> <dest_gcode> <log_file> [extra cli args...]
# Same shape as run_slice, but for the Part 2 (Support Interface Auto-Match)
# fixture: a single tshape.stl model, a caller-supplied filament list (the
# Part 1 fixture always loads two; Part 2's manual-mode identity checks need
# exactly one, to match how out/p2_baseline.gcode was itself recorded), and
# optional trailing generic --key=value CLI overrides (used for
# --enable-prime-tower=1; DynamicPrintAndCLIConfig::read_cli — see
# src/libslic3r/Config.cpp — accepts any FullPrintConfig key this way,
# dash-ified from its snake_case name).
run_slice_p2() {
    local overrides="$1" filaments="$2" dest="$3" logfile="$4"
    shift 4
    rm -f "$PLATE_OUT"
    "$EXE" --datadir "$DATADIR" \
        --load-settings "${MACHINE_PROFILE};${overrides}" \
        --load-filaments "${filaments}" \
        "$@" \
        --slice 0 --outputdir out "$TSHAPE" \
        > "$logfile" 2>&1
    local rc=$?
    if [ $rc -eq 0 ]; then
        if [ -f "$PLATE_OUT" ]; then
            mv -f "$PLATE_OUT" "$dest"
        else
            rc=1
        fi
    fi
    return $rc
}

# support_scope: filter a gcode stream (stdin) down to the regions relevant
# to the Part 2 feature - inside any "; FEATURE: Support" / "; FEATURE:
# Support interface" tagged section, plus toolchange lines (T<n>, M620*,
# M621*). Needed because tshape.stl's solid-infill chaining is independently
# confirmed (Task 3 report) to be non-deterministic run-to-run AND
# build-to-build in the base pipeline (reordered M73 markers / a
# differently-chunked "Internal solid infill" block) - a raw whole-file diff
# is NOT a valid identity check on this fixture.
#
# M73 progress-percentage lines are unconditionally dropped (not just left
# out of scope): Task 4's own diff investigation found the SAME M73 reorder
# non-determinism recurring *inside* "; FEATURE: Support..." tagged sections
# (M73 markers are interspersed by the time-estimator post-pass independent
# of feature boundaries), so leaving them in would let base-pipeline noise
# leak back into an otherwise-clean support-scoped comparison. See the Part
# 2 section below for exactly what this filter does and does not prove.
support_scope() {
    awk '
        /^M73/ { next }
        /^;.*FEATURE: /{ insupport = ($0 ~ /FEATURE: Support/) ? 1 : 0 }
        insupport { print; next }
        /^T[0-9]/ { print; next }
        /^M620/ { print; next }
        /^M621/ { print; next }
    '
}

# support_identical <fileA> <fileB> -> 0 if identical after normalize+support_scope
support_identical() {
    diff -q <(normalize "$1" | support_scope) <(normalize "$2" | support_scope) > /dev/null 2>&1
}

m620_count_of() { grep -cE "^M620 S" "$1"; }
total_layers_of() { grep -m1 "^; total layer number:" "$1" | grep -oE '[0-9]+' | head -1; }

# ---------------------------------------------------------------------------
# 1. Object mode (off-mode) — slice twice, byte-compare each vs baseline and
#    vs each other.
# ---------------------------------------------------------------------------
run_slice "$OBJ_OVERRIDES" "$OUT_OBJ_1" "out/verify_object_1.log"
obj1_rc=$?
if [ $obj1_rc -eq 0 ]; then record "object-run1-exit0" PASS "exit 0"
else record "object-run1-exit0" FAIL "exit $obj1_rc — see out/verify_object_1.log"; fi

run_slice "$OBJ_OVERRIDES" "$OUT_OBJ_2" "out/verify_object_2.log"
obj2_rc=$?
if [ $obj2_rc -eq 0 ]; then record "object-run2-exit0" PASS "exit 0"
else record "object-run2-exit0" FAIL "exit $obj2_rc — see out/verify_object_2.log"; fi

if [ $obj1_rc -eq 0 ]; then
    if byte_identical "$BASELINE" "$OUT_OBJ_1"; then
        record "object-run1-vs-baseline" PASS "byte-identical (normalized)"
    else
        record "object-run1-vs-baseline" FAIL "diff vs $BASELINE (normalized) — see diff manually"
    fi
else
    record "object-run1-vs-baseline" FAIL "skipped: run1 did not slice"
fi

if [ $obj2_rc -eq 0 ]; then
    if byte_identical "$BASELINE" "$OUT_OBJ_2"; then
        record "object-run2-vs-baseline" PASS "byte-identical (normalized)"
    else
        record "object-run2-vs-baseline" FAIL "diff vs $BASELINE (normalized) — see diff manually"
    fi
else
    record "object-run2-vs-baseline" FAIL "skipped: run2 did not slice"
fi

if [ $obj1_rc -eq 0 ] && [ $obj2_rc -eq 0 ]; then
    if byte_identical "$OUT_OBJ_1" "$OUT_OBJ_2"; then
        record "object-determinism" PASS "run1 == run2 (normalized)"
    else
        record "object-determinism" FAIL "run1 != run2 (normalized)"
    fi
else
    record "object-determinism" FAIL "skipped: one or both runs did not slice"
fi

# ---------------------------------------------------------------------------
# 2. nearest_wall mode (chameleon on) — slice twice, sanity-check run1,
#    byte-compare the two runs vs each other (determinism).
# ---------------------------------------------------------------------------
run_slice "$CHA_OVERRIDES" "$OUT_CHA_1" "out/verify_nearestwall_1.log"
cha1_rc=$?
if [ $cha1_rc -eq 0 ]; then record "nearestwall-run1-exit0" PASS "exit 0"
else record "nearestwall-run1-exit0" FAIL "exit $cha1_rc — see out/verify_nearestwall_1.log"; fi

run_slice "$CHA_OVERRIDES" "$OUT_CHA_2" "out/verify_nearestwall_2.log"
cha2_rc=$?
if [ $cha2_rc -eq 0 ]; then record "nearestwall-run2-exit0" PASS "exit 0"
else record "nearestwall-run2-exit0" FAIL "exit $cha2_rc — see out/verify_nearestwall_2.log"; fi

if [ $cha1_rc -eq 0 ]; then
    m620_count=$(grep -cE "^M620 S" "$OUT_CHA_1")
    if [ "$m620_count" -ge "$M620_MIN" ] && [ "$m620_count" -le "$M620_MAX" ]; then
        record "nearestwall-m620-bounds" PASS "M620 count = $m620_count (bound [$M620_MIN,$M620_MAX])"
    else
        record "nearestwall-m620-bounds" FAIL "M620 count = $m620_count, outside bound [$M620_MIN,$M620_MAX]"
    fi

    feature_count=$(grep -c "; FEATURE: Brim" "$OUT_CHA_1")
    if [ "$feature_count" -ge 1 ]; then
        record "nearestwall-feature-brim-present" PASS "'; FEATURE: Brim' occurs $feature_count time(s)"
    else
        record "nearestwall-feature-brim-present" FAIL "'; FEATURE: Brim' not found"
    fi
else
    record "nearestwall-m620-bounds" FAIL "skipped: run1 did not slice"
    record "nearestwall-feature-brim-present" FAIL "skipped: run1 did not slice"
fi

if [ $cha1_rc -eq 0 ] && [ $cha2_rc -eq 0 ]; then
    if byte_identical "$OUT_CHA_1" "$OUT_CHA_2"; then
        record "nearestwall-determinism" PASS "run1 == run2 (normalized)"
    else
        record "nearestwall-determinism" FAIL "run1 != run2 (normalized)"
    fi
else
    record "nearestwall-determinism" FAIL "skipped: one or both runs did not slice"
fi

# ---------------------------------------------------------------------------
# 3. Support Interface Auto-Match (Part 2) — tshape.stl fixture.
#
# CAVEAT (Task 3 report, reconfirmed here): tshape.stl's solid-infill
# chaining is run-to-run AND build-to-build non-deterministic in the base
# pipeline, unrelated to this feature — see support_scope()'s comment above.
# Every check below therefore compares only the support-region + toolchange
# content (support_identical), never a raw whole-file diff. That is
# sufficient to prove the new emission block introduces no divergence in the
# region it touches; it is NOT a whole-file determinism claim, and none is
# made here.
#
# CLI LIMITATION (same family as Part 1's precedent, see spike/FINDINGS.md):
# the CLI cannot assign per-object filaments to a plain STL, so tshape.stl —
# a single object — always resolves to exactly one used extruder no matter
# how many filaments are --load-filaments'd. Print::extruders() (Print.cpp)
# reflects real per-object usage, not the loaded-filament-profile count, so
# chameleon_assign_support_interfaces' own top-level guard
# (print.extruders().size() <= 1) returns before doing any work — even in
# nearest_surface mode on this fixture, interface_by_extruder stays empty
# for every support layer, so the new GCode.cpp emission block never finds a
# match to emit. The nearest_surface checks below therefore validate
# no-crash / well-formed output and correct feature/M620 presence, not real
# cross-extruder matching — that requires the user's multi-filament GUI
# fixture (see report for the definitive per-run evidence of whether the
# emission block fired).
# ---------------------------------------------------------------------------

# --- 3a. Manual mode, tower OFF: identity (support-scoped) vs the frozen
#         pre-Task-4 baseline. Single PLA filament, matching exactly how
#         p2_baseline.gcode was itself recorded (Task 3), so this is a true
#         apples-to-apples comparison.
run_slice_p2 "$P2_MANUAL_OVERRIDES" "$FIL_PLA" "$OUT_P2_MAN_OFF" "out/p2_manual_off.log"
p2man_off_rc=$?
if [ $p2man_off_rc -eq 0 ]; then record "p2-manual-off-exit0" PASS "exit 0"
else record "p2-manual-off-exit0" FAIL "exit $p2man_off_rc — see out/p2_manual_off.log"; fi

if [ $p2man_off_rc -eq 0 ]; then
    if support_identical "$P2_BASELINE" "$OUT_P2_MAN_OFF"; then
        record "p2-manual-off-vs-baseline" PASS "support-region + toolchange identical (normalized)"
    else
        record "p2-manual-off-vs-baseline" FAIL "support-region diff vs $P2_BASELINE — see diff manually"
    fi
else
    record "p2-manual-off-vs-baseline" FAIL "skipped: slice did not complete"
fi

# --- 3b. Manual mode, tower ON. NOTE: PrintApply.cpp's normalize_fdm_2
#         forces enable_prime_tower back to false whenever used_filaments==1
#         (PrintConfig.cpp ~7602/7683) — exactly this single-PLA,
#         single-STL-object fixture. "Tower ON" here therefore provably
#         collapses to the same tower-OFF code path; this check proves
#         passing the override doesn't crash and doesn't change the support
#         region. A real tower-on/support-interaction test needs the GUI
#         multi-filament fixture where a wipe tower can actually be built.
run_slice_p2 "$P2_MANUAL_OVERRIDES" "$FIL_PLA" "$OUT_P2_MAN_ON" "out/p2_manual_on.log" --enable-prime-tower=1
p2man_on_rc=$?
if [ $p2man_on_rc -eq 0 ]; then record "p2-manual-on-exit0" PASS "exit 0"
else record "p2-manual-on-exit0" FAIL "exit $p2man_on_rc — see out/p2_manual_on.log"; fi

if [ $p2man_on_rc -eq 0 ]; then
    if support_identical "$P2_BASELINE" "$OUT_P2_MAN_ON"; then
        record "p2-manual-on-vs-baseline" PASS "support-region + toolchange identical (normalized; tower forced off by used_filaments==1)"
    else
        record "p2-manual-on-vs-baseline" FAIL "support-region diff vs $P2_BASELINE — see diff manually"
    fi
else
    record "p2-manual-on-vs-baseline" FAIL "skipped: slice did not complete"
fi

# --- 3c. nearest_surface mode, tower OFF: no-crash + bounded M620 growth +
#         feature-tag presence. PLA+PETG loaded (2 filaments) so the pass's
#         own extruders()>1 gate has the best available chance to engage on
#         this CLI fixture; see the CLI LIMITATION note above for why it
#         still won't exercise real per-region matching here.
run_slice_p2 "$P2_NEAREST_OVERRIDES" "${FIL_PLA};${FIL_PETG}" "$OUT_P2_NS_OFF_1" "out/p2_nearest_off_1.log"
p2ns_off1_rc=$?
if [ $p2ns_off1_rc -eq 0 ]; then record "p2-nearest-off-exit0" PASS "exit 0"
else record "p2-nearest-off-exit0" FAIL "exit $p2ns_off1_rc — see out/p2_nearest_off_1.log"; fi

if [ $p2ns_off1_rc -eq 0 ]; then
    total_layers=$(total_layers_of "$OUT_P2_NS_OFF_1")
    [ -z "$total_layers" ] && total_layers=0
    m620_max=$((2 + 2 * 3 * total_layers))
    m620_count=$(m620_count_of "$OUT_P2_NS_OFF_1")
    if [ "$m620_count" -ge 2 ] && [ "$m620_count" -le "$m620_max" ]; then
        record "p2-nearest-off-m620-bounds" PASS "M620 count = $m620_count (bound [2,$m620_max], total_layers=$total_layers)"
    else
        record "p2-nearest-off-m620-bounds" FAIL "M620 count = $m620_count, outside bound [2,$m620_max]"
    fi

    feature_count=$(grep -c "; FEATURE: Support interface" "$OUT_P2_NS_OFF_1")
    if [ "$feature_count" -ge 1 ]; then
        record "p2-nearest-off-feature-present" PASS "'; FEATURE: Support interface' occurs $feature_count time(s)"
    else
        record "p2-nearest-off-feature-present" FAIL "'; FEATURE: Support interface' not found"
    fi
else
    record "p2-nearest-off-m620-bounds" FAIL "skipped: run did not slice"
    record "p2-nearest-off-feature-present" FAIL "skipped: run did not slice"
fi

# --- 3d. nearest_surface mode, tower ON: same sanity bar, tower override
#         applied (see 3b's note — it collapses to tower-off here too).
run_slice_p2 "$P2_NEAREST_OVERRIDES" "${FIL_PLA};${FIL_PETG}" "$OUT_P2_NS_ON" "out/p2_nearest_on.log" --enable-prime-tower=1
p2ns_on_rc=$?
if [ $p2ns_on_rc -eq 0 ]; then record "p2-nearest-on-exit0" PASS "exit 0"
else record "p2-nearest-on-exit0" FAIL "exit $p2ns_on_rc — see out/p2_nearest_on.log"; fi

if [ $p2ns_on_rc -eq 0 ]; then
    total_layers=$(total_layers_of "$OUT_P2_NS_ON")
    [ -z "$total_layers" ] && total_layers=0
    m620_max=$((2 + 2 * 3 * total_layers))
    m620_count=$(m620_count_of "$OUT_P2_NS_ON")
    if [ "$m620_count" -ge 2 ] && [ "$m620_count" -le "$m620_max" ]; then
        record "p2-nearest-on-m620-bounds" PASS "M620 count = $m620_count (bound [2,$m620_max], total_layers=$total_layers)"
    else
        record "p2-nearest-on-m620-bounds" FAIL "M620 count = $m620_count, outside bound [2,$m620_max]"
    fi

    feature_count=$(grep -c "; FEATURE: Support interface" "$OUT_P2_NS_ON")
    if [ "$feature_count" -ge 1 ]; then
        record "p2-nearest-on-feature-present" PASS "'; FEATURE: Support interface' occurs $feature_count time(s)"
    else
        record "p2-nearest-on-feature-present" FAIL "'; FEATURE: Support interface' not found"
    fi
else
    record "p2-nearest-on-m620-bounds" FAIL "skipped: run did not slice"
    record "p2-nearest-on-feature-present" FAIL "skipped: run did not slice"
fi

# --- 3e. Determinism repeat: nearest_surface, tower OFF, two consecutive
#         slices, support-scoped compare (per the CAVEAT above).
run_slice_p2 "$P2_NEAREST_OVERRIDES" "${FIL_PLA};${FIL_PETG}" "$OUT_P2_NS_OFF_2" "out/p2_nearest_off_2.log"
p2ns_off2_rc=$?
if [ $p2ns_off2_rc -eq 0 ]; then record "p2-nearest-determinism-run2-exit0" PASS "exit 0"
else record "p2-nearest-determinism-run2-exit0" FAIL "exit $p2ns_off2_rc — see out/p2_nearest_off_2.log"; fi

if [ $p2ns_off1_rc -eq 0 ] && [ $p2ns_off2_rc -eq 0 ]; then
    if support_identical "$OUT_P2_NS_OFF_1" "$OUT_P2_NS_OFF_2"; then
        record "p2-nearest-determinism" PASS "run1 == run2, support-region + toolchange (normalized)"
    else
        record "p2-nearest-determinism" FAIL "run1 != run2, support-region + toolchange (normalized)"
    fi
else
    record "p2-nearest-determinism" FAIL "skipped: one or both runs did not slice"
fi

# ---------------------------------------------------------------------------
# Report
# ---------------------------------------------------------------------------
echo ""
printf "%-32s %-6s %s\n" "CHECK" "RESULT" "DETAIL"
printf "%-32s %-6s %s\n" "--------------------------------" "------" "----------------------------------------"
for row in "${RESULTS[@]}"; do
    IFS='|' read -r name status detail <<< "$row"
    printf "%-32s %-6s %s\n" "$name" "$status" "$detail"
done
echo ""

total=${#RESULTS[@]}
passed=$((total - FAILS))
echo "${passed}/${total} checks passed."

if [ "$FAILS" -eq 0 ]; then
    echo "RESULT: ALL PASS"
    exit 0
else
    echo "RESULT: FAIL ($FAILS check(s) failed)"
    exit 1
fi
