#!/usr/bin/env bash
# spike/verify_paintdepth.sh
#
# Paint Depth (perimeter-aware paint-depth clamp, bounded by default +
# vertical-bleed stage 2) — Task 4 repeatable regression check for:
#
#   A. UNPAINTED-fixture inertness: the feature must have NO effect on an
#      unpainted object's toolpath, even though its config defaults changed
#      behavior for PAINTED objects (paint_depth_mode default WALLS,
#      mmu_segmented_region_interlocking_depth default flipped 0 -> 0.1;
#      that default was 0.3 until the bleed-and-walls fix wave lowered it,
#      see fix-wave F4 in PrintConfig.cpp / PaintDepth.hpp).
#      Checked two ways:
#        A1. byte-parity (normalized) vs a FROZEN baseline gcode recorded
#            from a one-time build of this exact worktree at the feature's
#            merge-base commit (c345859f55 — the last commit with NO code
#            diff from this branch's pre-Task-1 state; see "Baseline
#            provenance" below for the honest procedure used to produce it).
#        A2. determinism — two consecutive slices of the CURRENT binary,
#            normalized-identical to each other (independent of the baseline
#            question; catches any nondeterminism the feature itself might
#            introduce even if it never diverges from the baseline).
#   B. (folded into A2) determinism repeat, same run pair.
#   C. Config surface checks (CLI config-load evidence, i.e. inspecting the
#      RESOLVED value in the output gcode's CONFIG_BLOCK dump — the same
#      technique the supports feature's verify_chameleon.sh legacy-key
#      checks use — plus the loader's "no substitutions performed" log line
#      as supporting evidence the file loaded cleanly):
#        C1. defaults resolve: paint_depth_mode=walls, paint_depth_walls=3,
#            paint_depth_mm=1.5, mmu_segmented_region_interlocking_depth=0.1.
#        C2. legacy NONZERO mmu_segmented_region_max_width (old key, still a
#            real ConfigOptionDef — legacy-parse-only per Task 1) maps to
#            paint_depth_mode=millimeters with paint_depth_mm carrying the
#            legacy value verbatim (PrintConfigDef::handle_legacy_composite).
#        C3. legacy ZERO mmu_segmented_region_max_width does NOT carry
#            forward as paint_depth_mode=unlimited — it falls through to the
#            option's own default (walls), per Task 1's deliberate
#            "bounded-by-default must apply to every reslice of an old
#            project" decision (task-1-report.md).
#
# Painted-fixture CLI checks are DELIBERATELY NOT attempted here: Task 2/3's
# harness (tests/libslic3r/test_paint_depth_clamp.cpp, [paintdepth] tag)
# already validates painted behavior end-to-end (real painted mesh -> sliced
# PrintObject -> inspected applied region geometry) at the unit level, which
# sidesteps the known CLI limitation that GUI-exported painted project 3mfs
# segfault the CLI (see spike/FINDINGS.md, supports feature). This narrows
# this script's job to exactly the three items above, per the Task 4 plan.
#
# --- Baseline provenance (honest procedure) -------------------------------
# out/paintdepth_baseline.gcode was produced by:
#   1. `git worktree add ../SnapmakerOrcaBaseline c345859f55` (c345859f55 is
#      this branch's merge-base commit — confirmed via
#      `git diff --stat c345859f55 ed726d71e9~1 -- . ':!docs' ':!.superpowers'`
#      returning EMPTY, i.e. byte-identical source tree to the commit
#      immediately before Task 1's first code change; the two intervening
#      "docs(paint-depth): ..." commits touch only docs/superpowers/).
#   2. Configured cmake identically to Task 1's worktree setup
#      (CMAKE_PREFIX_PATH against the main checkout's deps, VS17/x64,
#      Release) and built ONLY the app executable target
#      (Snapmaker_Orca_app_gui — NOT the full ALL_BUILD gate, since this is a
#      throwaway comparison binary, not a change to the feature branch
#      itself; no source in the feature branch was touched by this step).
#   3. Sliced cube30.stl with spike_paintdepth_overrides.json (no paint-depth
#      keys referenced, so the same overrides file loads cleanly on both the
#      baseline and current binaries) via that baseline exe, recorded the
#      output as out/paintdepth_baseline.gcode, then removed the temporary
#      worktree and its build tree.
# This baseline is FROZEN (committed to the repo) exactly like the supports
# feature's out/baseline_clean.gcode / out/p2_baseline.gcode — it is not
# regenerated by this script and should only be re-recorded if the
# merge-base commit itself changes (a rebase/re-plan of this feature).
#
# Run from anywhere; the script cd's into its own directory (spike/) first.
# Plain bash (Git Bash on Windows is fine) — uses process substitution, so
# `bash verify_paintdepth.sh` / `./verify_paintdepth.sh`, not `sh ...`.
# Requires a built snapmaker-orca.exe (../build/src/Release/) for the branch
# under test — NOT the baseline binary, which is throwaway/already removed.

set -u
cd "$(dirname "${BASH_SOURCE[0]}")"

# ---------------------------------------------------------------------------
# Harness fixtures
# ---------------------------------------------------------------------------
EXE="../build/src/Release/snapmaker-orca.exe"
DATADIR="C:/Dev/SnapmakerOrcaNext/spike/datadir"
MACHINE_PROFILE="../resources/profiles/BBL/machine/Bambu Lab X1 Carbon 0.4 nozzle.json"
FIL_PLA="../resources/profiles/BBL/filament/Bambu PLA Basic @BBL X1C.json"

DEFAULTS_OVERRIDES="spike_paintdepth_overrides.json"            # no paint_depth_* keys — loads on baseline AND current binaries
LEGACY_NONZERO_OVERRIDES="spike_paintdepth_legacy_nonzero.json" # mmu_segmented_region_max_width = 0.8 (old key, nonzero)
LEGACY_ZERO_OVERRIDES="spike_paintdepth_legacy_zero.json"       # mmu_segmented_region_max_width = 0 (old key, present but zero)

BASELINE="out/paintdepth_baseline.gcode"
PLATE_OUT="out/plate_1.gcode"   # snapmaker-orca.exe's fixed single-object-plate output name

OUT_DEFAULTS_1="out/paintdepth_defaults_1.gcode"
OUT_DEFAULTS_2="out/paintdepth_defaults_2.gcode"
OUT_LEGACY_NONZERO="out/paintdepth_legacy_nonzero.gcode"
OUT_LEGACY_ZERO="out/paintdepth_legacy_zero.gcode"

# ---------------------------------------------------------------------------
# Preflight — fail fast with a clear message if the harness itself isn't set
# up, rather than limping through every check reporting confusing FAILs.
# ---------------------------------------------------------------------------
preflight_fail=0
for f in "$EXE" "$MACHINE_PROFILE" "$FIL_PLA" "$DEFAULTS_OVERRIDES" \
         "$LEGACY_NONZERO_OVERRIDES" "$LEGACY_ZERO_OVERRIDES" "$BASELINE" \
         cube30.stl normalize_strip_slivers.awk; do
    if [ ! -f "$f" ]; then
        echo "PREFLIGHT FAIL: missing required file: $f" >&2
        preflight_fail=1
    fi
done
if [ ! -d "$DATADIR" ]; then
    echo "PREFLIGHT FAIL: missing datadir: $DATADIR" >&2
    preflight_fail=1
fi
if [ "$preflight_fail" -ne 0 ]; then
    echo "Aborting: harness prerequisites not met (see above). Build snapmaker-orca.exe and/or check spike/ fixtures." >&2
    exit 2
fi

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
RESULTS=()   # "name|PASS/FAIL|detail"
FAILS=0

record() {
    local name="$1" status="$2" detail="$3"
    RESULTS+=("${name}|${status}|${detail}")
    if [ "$status" != "PASS" ]; then
        FAILS=$((FAILS + 1))
    fi
}

# normalize <file> -> stdout
# Reuses the supports feature's proven strip set verbatim (spike/verify_chameleon.sh,
# C:\Dev\SnapmakerOrcaSupports\spike\verify_chameleon.sh — same repo history, same
# gcode pipeline, so the same run-to-run/build-to-build noise sources apply):
#   - "; generated by ..." header (build string + wall-clock timestamp)
#   - "; at " lines (defensive, as upstream)
#   - M73/M73.2 progress-percentage lines (time-estimator reorder noise)
#   - "; model printing time ...", "; estimated first layer printing time ...",
#     "; filament used [mm]"/"[cm3]" — downstream fallout of time/flow
#     estimation, not toolpath content
#   - the "id:<N> copy 0" per-object numeric id suffix (run-to-run nondeterministic)
#   - degenerate solid-infill micro-extrusion slivers, via
#     normalize_strip_slivers.awk (C:\Dev\SnapmakerOrcaSupports\solid_infill_nondeterminism.md)
#     — empirically confirmed still necessary here too: a raw diff of two
#     back-to-back identical-command slices of THIS fixture differs; the
#     normalized diff (including this awk pass) is empty (verified directly
#     while writing this script).
# PLUS three paint-depth-specific strips, all CONFIG_BLOCK dump lines that
# are new or changed-default as of this feature and therefore legitimately
# differ from the pre-feature baseline on an UNPAINTED object even though
# the feature has zero effect on that object's actual toolpath:
#   - "; paint_depth_mode = ...", "; paint_depth_walls = ...",
#     "; paint_depth_mm = ...", "; paint_infill_override = ..." — these four
#     keys did not exist in the pre-feature (baseline) CONFIG_BLOCK at all,
#     so the line is simply ABSENT there; stripping it from both sides keeps
#     the line-count symmetric.
#   - "; mmu_segmented_region_interlocking_depth = ..." — same key both
#     sides, but Task 1 flipped its default 0 -> 0.3, so the VALUE differs
#     even on an unpainted object; this is a config-dump-only difference
#     (interlocking is only ever consumed when is_mm_painted(), confirmed in
#     Task 2's report) not a toolpath difference.
# Confirmed empirically (see "config surface checks" section below, which
# asserts each of these lines' RESOLVED values directly) that stripping them
# here does not mask a real behavioral difference — it is exactly the set of
# lines this feature is EXPECTED to change on any object, painted or not.
normalize() {
    sed -e '/^; generated by/d' \
        -e '/^; at /d' \
        -e '/^M73/d' \
        -e '/^; model printing time/d' \
        -e '/^; estimated first layer printing time/d' \
        -e '/^; filament used/d' \
        -e '/^; paint_depth_mode/d' \
        -e '/^; paint_depth_walls/d' \
        -e '/^; paint_depth_mm/d' \
        -e '/^; paint_infill_override/d' \
        -e '/^; mmu_segmented_region_interlocking_depth/d' \
        -e 's/id:[0-9]\+ copy 0/id:X copy 0/' \
        "$1" \
    | awk -f normalize_strip_slivers.awk
}

# byte_identical <fileA> <fileB> -> 0 if identical after normalize, 1 otherwise
byte_identical() {
    diff -q <(normalize "$1") <(normalize "$2") > /dev/null 2>&1
}

# run_slice <overrides_json> <dest_gcode> <log_file> [extra cli args...]
# Slices cube30.stl with the given process-overrides JSON, moving the CLI's
# fixed plate_1.gcode output to a stable per-run name so the next run doesn't
# clobber it. Returns the exe's exit code (or 1 if it exited 0 but produced
# no plate_1.gcode).
run_slice() {
    local overrides="$1" dest="$2" logfile="$3"
    shift 3
    rm -f "$PLATE_OUT"
    "$EXE" --datadir "$DATADIR" \
        --load-settings "${MACHINE_PROFILE};${overrides}" \
        --load-filaments "${FIL_PLA}" \
        "$@" \
        --slice 0 --outputdir out cube30.stl \
        > "$logfile" 2>&1
    local rc=$?
    if [ $rc -eq 0 ]; then
        if [ -f "$PLATE_OUT" ]; then
            mv -f "$PLATE_OUT" "$dest"
        else
            rc=1
        fi
    fi
    return $rc
}

resolved_value_of() {
    # resolved_value_of <file> <key> -> the value after "; <key> = " (first match)
    grep -m1 -E "^; $2 = " "$1" | sed -E "s/^; $2 = //"
}

# ---------------------------------------------------------------------------
# A. UNPAINTED-fixture inertness — slice twice, byte-compare each vs the
#    frozen baseline, and the two runs vs each other (determinism).
# ---------------------------------------------------------------------------
run_slice "$DEFAULTS_OVERRIDES" "$OUT_DEFAULTS_1" "out/paintdepth_defaults_1.log"
d1_rc=$?
if [ $d1_rc -eq 0 ]; then record "unpainted-run1-exit0" PASS "exit 0"
else record "unpainted-run1-exit0" FAIL "exit $d1_rc — see out/paintdepth_defaults_1.log"; fi

run_slice "$DEFAULTS_OVERRIDES" "$OUT_DEFAULTS_2" "out/paintdepth_defaults_2.log"
d2_rc=$?
if [ $d2_rc -eq 0 ]; then record "unpainted-run2-exit0" PASS "exit 0"
else record "unpainted-run2-exit0" FAIL "exit $d2_rc — see out/paintdepth_defaults_2.log"; fi

if [ $d1_rc -eq 0 ]; then
    if byte_identical "$BASELINE" "$OUT_DEFAULTS_1"; then
        record "unpainted-run1-vs-baseline" PASS "byte-identical (normalized) — feature is inert without paint"
    else
        record "unpainted-run1-vs-baseline" FAIL "diff vs $BASELINE (normalized) — see diff manually"
    fi
else
    record "unpainted-run1-vs-baseline" FAIL "skipped: run1 did not slice"
fi

if [ $d2_rc -eq 0 ]; then
    if byte_identical "$BASELINE" "$OUT_DEFAULTS_2"; then
        record "unpainted-run2-vs-baseline" PASS "byte-identical (normalized) — feature is inert without paint"
    else
        record "unpainted-run2-vs-baseline" FAIL "diff vs $BASELINE (normalized) — see diff manually"
    fi
else
    record "unpainted-run2-vs-baseline" FAIL "skipped: run2 did not slice"
fi

if [ $d1_rc -eq 0 ] && [ $d2_rc -eq 0 ]; then
    if byte_identical "$OUT_DEFAULTS_1" "$OUT_DEFAULTS_2"; then
        record "unpainted-determinism" PASS "run1 == run2 (normalized)"
    else
        record "unpainted-determinism" FAIL "run1 != run2 (normalized)"
    fi
else
    record "unpainted-determinism" FAIL "skipped: one or both runs did not slice"
fi

# ---------------------------------------------------------------------------
# C1. Config surface — defaults resolve as designed (Task 1).
# ---------------------------------------------------------------------------
if [ $d1_rc -eq 0 ]; then
    checks=(
        "paint_depth_mode|walls"
        "paint_depth_walls|3"
        "paint_depth_mm|1.5"
        "mmu_segmented_region_interlocking_depth|0.1"
    )
    for c in "${checks[@]}"; do
        key="${c%%|*}"; expected="${c##*|}"
        actual="$(resolved_value_of "$OUT_DEFAULTS_1" "$key")"
        if [ "$actual" = "$expected" ]; then
            record "defaults-$key" PASS "= $actual"
        else
            record "defaults-$key" FAIL "expected '$expected', got '$actual'"
        fi
    done
else
    record "defaults-paint_depth_mode" FAIL "skipped: run1 did not slice"
    record "defaults-paint_depth_walls" FAIL "skipped: run1 did not slice"
    record "defaults-paint_depth_mm" FAIL "skipped: run1 did not slice"
    record "defaults-mmu_segmented_region_interlocking_depth" FAIL "skipped: run1 did not slice"
fi

# ---------------------------------------------------------------------------
# C2. Legacy NONZERO mmu_segmented_region_max_width -> millimeters mode,
#     carrying the legacy value verbatim into paint_depth_mm.
#     --debug=3 bumps BOOST_LOG_TRIVIAL(info) to visible (CLI defaults to
#     "warning") so the loader's "no substitutions performed" line is
#     actually emitted — same technique as verify_chameleon.sh's legacy-key
#     checks (see that script's section 3c comment for the full rationale).
# ---------------------------------------------------------------------------
run_slice "$LEGACY_NONZERO_OVERRIDES" "$OUT_LEGACY_NONZERO" "out/paintdepth_legacy_nonzero.log" --debug=3
lnz_rc=$?
if [ $lnz_rc -eq 0 ]; then record "legacy-nonzero-exit0" PASS "exit 0"
else record "legacy-nonzero-exit0" FAIL "exit $lnz_rc — see out/paintdepth_legacy_nonzero.log"; fi

if [ $lnz_rc -eq 0 ]; then
    if grep -qE "no substitutions performed from file .*spike_paintdepth_legacy_nonzero\.json" "out/paintdepth_legacy_nonzero.log"; then
        record "legacy-nonzero-load-clean" PASS "config file loaded without deserialize-failure substitution"
    else
        record "legacy-nonzero-load-clean" FAIL "expected 'no substitutions performed from file ...spike_paintdepth_legacy_nonzero.json' in out/paintdepth_legacy_nonzero.log"
    fi

    mode_actual="$(resolved_value_of "$OUT_LEGACY_NONZERO" "paint_depth_mode")"
    if [ "$mode_actual" = "millimeters" ]; then
        record "legacy-nonzero-mode-millimeters" PASS "paint_depth_mode = millimeters"
    else
        record "legacy-nonzero-mode-millimeters" FAIL "expected 'millimeters', got '$mode_actual'"
    fi

    mm_actual="$(resolved_value_of "$OUT_LEGACY_NONZERO" "paint_depth_mm")"
    if [ "$mm_actual" = "0.8" ]; then
        record "legacy-nonzero-mm-value" PASS "paint_depth_mm = 0.8 (legacy mmu_segmented_region_max_width value carried verbatim)"
    else
        record "legacy-nonzero-mm-value" FAIL "expected '0.8', got '$mm_actual'"
    fi
else
    record "legacy-nonzero-load-clean" FAIL "skipped: run did not slice"
    record "legacy-nonzero-mode-millimeters" FAIL "skipped: run did not slice"
    record "legacy-nonzero-mm-value" FAIL "skipped: run did not slice"
fi

# ---------------------------------------------------------------------------
# C3. Legacy ZERO mmu_segmented_region_max_width (key present, value 0) does
#     NOT carry forward as "unlimited" — falls through to the option's own
#     default (walls), the deliberate bounded-by-default-on-reslice decision
#     documented in task-1-report.md.
# ---------------------------------------------------------------------------
run_slice "$LEGACY_ZERO_OVERRIDES" "$OUT_LEGACY_ZERO" "out/paintdepth_legacy_zero.log" --debug=3
lz_rc=$?
if [ $lz_rc -eq 0 ]; then record "legacy-zero-exit0" PASS "exit 0"
else record "legacy-zero-exit0" FAIL "exit $lz_rc — see out/paintdepth_legacy_zero.log"; fi

if [ $lz_rc -eq 0 ]; then
    if grep -qE "no substitutions performed from file .*spike_paintdepth_legacy_zero\.json" "out/paintdepth_legacy_zero.log"; then
        record "legacy-zero-load-clean" PASS "config file loaded without deserialize-failure substitution"
    else
        record "legacy-zero-load-clean" FAIL "expected 'no substitutions performed from file ...spike_paintdepth_legacy_zero.json' in out/paintdepth_legacy_zero.log"
    fi

    mode_actual="$(resolved_value_of "$OUT_LEGACY_ZERO" "paint_depth_mode")"
    if [ "$mode_actual" = "walls" ]; then
        record "legacy-zero-mode-defaults-to-walls" PASS "paint_depth_mode = walls (NOT unlimited — bounded-by-default preserved on reslice)"
    else
        record "legacy-zero-mode-defaults-to-walls" FAIL "expected 'walls', got '$mode_actual'"
    fi

    mm_actual="$(resolved_value_of "$OUT_LEGACY_ZERO" "paint_depth_mm")"
    if [ "$mm_actual" = "1.5" ]; then
        record "legacy-zero-mm-stays-default" PASS "paint_depth_mm = 1.5 (own default, not consulted in walls mode anyway)"
    else
        record "legacy-zero-mm-stays-default" FAIL "expected '1.5', got '$mm_actual'"
    fi
else
    record "legacy-zero-load-clean" FAIL "skipped: run did not slice"
    record "legacy-zero-mode-defaults-to-walls" FAIL "skipped: run did not slice"
    record "legacy-zero-mm-stays-default" FAIL "skipped: run did not slice"
fi

# ---------------------------------------------------------------------------
# Report
# ---------------------------------------------------------------------------
echo ""
printf "%-38s %-6s %s\n" "CHECK" "RESULT" "DETAIL"
printf "%-38s %-6s %s\n" "--------------------------------------" "------" "----------------------------------------"
for row in "${RESULTS[@]}"; do
    IFS='|' read -r name status detail <<< "$row"
    printf "%-38s %-6s %s\n" "$name" "$status" "$detail"
done
echo ""

total=${#RESULTS[@]}
passed=$((total - FAILS))
echo "${passed}/${total} checks passed."

if [ "$FAILS" -eq 0 ]; then
    echo "RESULT: ALL PASS"
    exit 0
else
    echo "RESULT: FAIL ($FAILS check(s) failed)"
    exit 1
fi
