#!/usr/bin/env bash
# spike/verify_chameleon.sh
#
# Chameleon Brim — repeatable regression check for:
#   1. Off-mode ("object" brim_filament_source) byte-identity vs the frozen
#      baseline_clean.gcode, AND determinism of two consecutive off-mode slices.
#   2. nearest_wall-mode sanity (exit 0, M620 count within the switch-count
#      guard bound, brim feature present) AND determinism of two consecutive
#      nearest_wall slices.
#
# Run from anywhere; the script cd's into its own directory (spike/) first so
# all the relative harness paths below resolve the same way regardless of the
# caller's cwd. Requires a built snapmaker-orca.exe (../build/src/Release/).
#
# Plain bash (Git Bash on Windows is fine) — uses process substitution, so
# `bash verify_chameleon.sh` / `./verify_chameleon.sh`, not `sh verify_chameleon.sh`.

set -u
cd "$(dirname "${BASH_SOURCE[0]}")"

# ---------------------------------------------------------------------------
# Harness fixtures (per spike/FINDINGS.md harness notes)
# ---------------------------------------------------------------------------
EXE="../build/src/Release/snapmaker-orca.exe"
DATADIR="C:/Dev/SnapmakerOrcaSupports/spike/datadir"
MACHINE_PROFILE="../resources/profiles/BBL/machine/Bambu Lab X1 Carbon 0.4 nozzle.json"
FIL_PLA="../resources/profiles/BBL/filament/Bambu PLA Basic @BBL X1C.json"
FIL_PETG="../resources/profiles/BBL/filament/Bambu PETG Basic @BBL X1C.json"
OBJ_OVERRIDES="spike_process_overrides.json"      # implicit brim_filament_source = object
CHA_OVERRIDES="spike_chameleon_overrides.json"    # brim_filament_source = nearest_wall

BASELINE="out/baseline_clean.gcode"
PLATE_OUT="out/plate_1.gcode"   # snapmaker-orca.exe's fixed multi-object-plate output name

OUT_OBJ_1="out/verify_object_1.gcode"
OUT_OBJ_2="out/verify_object_2.gcode"
OUT_CHA_1="out/verify_nearestwall_1.gcode"
OUT_CHA_2="out/verify_nearestwall_2.gcode"

M620_MIN=2
M620_MAX=10

# ---------------------------------------------------------------------------
# Preflight — fail fast with a clear message if the harness itself isn't set up,
# rather than limping through every check reporting confusing FAILs.
# ---------------------------------------------------------------------------
preflight_fail=0
for f in "$EXE" "$MACHINE_PROFILE" "$FIL_PLA" "$FIL_PETG" "$OBJ_OVERRIDES" "$CHA_OVERRIDES" "$BASELINE" cube30.stl cube30b.stl; do
    if [ ! -f "$f" ]; then
        echo "PREFLIGHT FAIL: missing required file: $f" >&2
        preflight_fail=1
    fi
done
if [ ! -d "$DATADIR" ]; then
    echo "PREFLIGHT FAIL: missing datadir: $DATADIR" >&2
    preflight_fail=1
fi
if [ "$preflight_fail" -ne 0 ]; then
    echo "Aborting: harness prerequisites not met (see above). Build snapmaker-orca.exe and/or check spike/ fixtures." >&2
    exit 2
fi

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
RESULTS=()   # "name|PASS/FAIL|detail"
FAILS=0

record() {
    local name="$1" status="$2" detail="$3"
    RESULTS+=("${name}|${status}|${detail}")
    if [ "$status" != "PASS" ]; then
        FAILS=$((FAILS + 1))
    fi
}

# Strip lines/fields known (and verified, see Task 4 report) to legitimately
# differ run-to-run or mode-to-mode without indicating a real regression:
#   - "; generated by ..." header line (build string + wall-clock timestamp)
#   - lines starting "; at " (defensive; currently folded into the line above,
#     kept as its own filter in case a future build ever splits it out)
#   - "; brim_filament_source = ..." config-dump line (value differs
#     object vs nearest_wall by design, and is entirely absent from the
#     pre-Task-3 baseline_clean.gcode, which predates that config key)
#   - the "id:<N> copy 0" suffix on "; printing object ..." / "; stop printing
#     object ..." comments — this per-object numeric id is run-to-run
#     nondeterministic (confirmed by back-to-back identical-command runs in
#     Task 4); everything else on those lines, including the stable
#     "unique label id: NN" companion comment, is left untouched.
normalize() {
    sed -e '/^; generated by/d' \
        -e '/^; at /d' \
        -e '/^; brim_filament_source/d' \
        -e 's/id:[0-9]\+ copy 0/id:X copy 0/' \
        "$1"
}

# byte_identical <fileA> <fileB> -> 0 if identical after normalize, 1 otherwise
byte_identical() {
    diff -q <(normalize "$1") <(normalize "$2") > /dev/null 2>&1
}

# run_slice <overrides_json> <dest_gcode> <log_file>
# Slices the two-cube fixture with the given process-overrides JSON, moving
# the CLI's fixed plate_1.gcode output to a stable per-run name so the next
# run doesn't clobber it. Returns the exe's exit code (or 1 if it exited 0
# but produced no plate_1.gcode).
run_slice() {
    local overrides="$1" dest="$2" logfile="$3"
    rm -f "$PLATE_OUT"
    "$EXE" --datadir "$DATADIR" \
        --load-settings "${MACHINE_PROFILE};${overrides}" \
        --load-filaments "${FIL_PLA};${FIL_PETG}" \
        --slice 0 --outputdir out cube30.stl cube30b.stl \
        > "$logfile" 2>&1
    local rc=$?
    if [ $rc -eq 0 ]; then
        if [ -f "$PLATE_OUT" ]; then
            mv -f "$PLATE_OUT" "$dest"
        else
            rc=1
        fi
    fi
    return $rc
}

# ---------------------------------------------------------------------------
# 1. Object mode (off-mode) — slice twice, byte-compare each vs baseline and
#    vs each other.
# ---------------------------------------------------------------------------
run_slice "$OBJ_OVERRIDES" "$OUT_OBJ_1" "out/verify_object_1.log"
obj1_rc=$?
if [ $obj1_rc -eq 0 ]; then record "object-run1-exit0" PASS "exit 0"
else record "object-run1-exit0" FAIL "exit $obj1_rc — see out/verify_object_1.log"; fi

run_slice "$OBJ_OVERRIDES" "$OUT_OBJ_2" "out/verify_object_2.log"
obj2_rc=$?
if [ $obj2_rc -eq 0 ]; then record "object-run2-exit0" PASS "exit 0"
else record "object-run2-exit0" FAIL "exit $obj2_rc — see out/verify_object_2.log"; fi

if [ $obj1_rc -eq 0 ]; then
    if byte_identical "$BASELINE" "$OUT_OBJ_1"; then
        record "object-run1-vs-baseline" PASS "byte-identical (normalized)"
    else
        record "object-run1-vs-baseline" FAIL "diff vs $BASELINE (normalized) — see diff manually"
    fi
else
    record "object-run1-vs-baseline" FAIL "skipped: run1 did not slice"
fi

if [ $obj2_rc -eq 0 ]; then
    if byte_identical "$BASELINE" "$OUT_OBJ_2"; then
        record "object-run2-vs-baseline" PASS "byte-identical (normalized)"
    else
        record "object-run2-vs-baseline" FAIL "diff vs $BASELINE (normalized) — see diff manually"
    fi
else
    record "object-run2-vs-baseline" FAIL "skipped: run2 did not slice"
fi

if [ $obj1_rc -eq 0 ] && [ $obj2_rc -eq 0 ]; then
    if byte_identical "$OUT_OBJ_1" "$OUT_OBJ_2"; then
        record "object-determinism" PASS "run1 == run2 (normalized)"
    else
        record "object-determinism" FAIL "run1 != run2 (normalized)"
    fi
else
    record "object-determinism" FAIL "skipped: one or both runs did not slice"
fi

# ---------------------------------------------------------------------------
# 2. nearest_wall mode (chameleon on) — slice twice, sanity-check run1,
#    byte-compare the two runs vs each other (determinism).
# ---------------------------------------------------------------------------
run_slice "$CHA_OVERRIDES" "$OUT_CHA_1" "out/verify_nearestwall_1.log"
cha1_rc=$?
if [ $cha1_rc -eq 0 ]; then record "nearestwall-run1-exit0" PASS "exit 0"
else record "nearestwall-run1-exit0" FAIL "exit $cha1_rc — see out/verify_nearestwall_1.log"; fi

run_slice "$CHA_OVERRIDES" "$OUT_CHA_2" "out/verify_nearestwall_2.log"
cha2_rc=$?
if [ $cha2_rc -eq 0 ]; then record "nearestwall-run2-exit0" PASS "exit 0"
else record "nearestwall-run2-exit0" FAIL "exit $cha2_rc — see out/verify_nearestwall_2.log"; fi

if [ $cha1_rc -eq 0 ]; then
    m620_count=$(grep -cE "^M620 S" "$OUT_CHA_1")
    if [ "$m620_count" -ge "$M620_MIN" ] && [ "$m620_count" -le "$M620_MAX" ]; then
        record "nearestwall-m620-bounds" PASS "M620 count = $m620_count (bound [$M620_MIN,$M620_MAX])"
    else
        record "nearestwall-m620-bounds" FAIL "M620 count = $m620_count, outside bound [$M620_MIN,$M620_MAX]"
    fi

    feature_count=$(grep -c "; FEATURE: Brim" "$OUT_CHA_1")
    if [ "$feature_count" -ge 1 ]; then
        record "nearestwall-feature-brim-present" PASS "'; FEATURE: Brim' occurs $feature_count time(s)"
    else
        record "nearestwall-feature-brim-present" FAIL "'; FEATURE: Brim' not found"
    fi
else
    record "nearestwall-m620-bounds" FAIL "skipped: run1 did not slice"
    record "nearestwall-feature-brim-present" FAIL "skipped: run1 did not slice"
fi

if [ $cha1_rc -eq 0 ] && [ $cha2_rc -eq 0 ]; then
    if byte_identical "$OUT_CHA_1" "$OUT_CHA_2"; then
        record "nearestwall-determinism" PASS "run1 == run2 (normalized)"
    else
        record "nearestwall-determinism" FAIL "run1 != run2 (normalized)"
    fi
else
    record "nearestwall-determinism" FAIL "skipped: one or both runs did not slice"
fi

# ---------------------------------------------------------------------------
# Report
# ---------------------------------------------------------------------------
echo ""
printf "%-32s %-6s %s\n" "CHECK" "RESULT" "DETAIL"
printf "%-32s %-6s %s\n" "--------------------------------" "------" "----------------------------------------"
for row in "${RESULTS[@]}"; do
    IFS='|' read -r name status detail <<< "$row"
    printf "%-32s %-6s %s\n" "$name" "$status" "$detail"
done
echo ""

total=${#RESULTS[@]}
passed=$((total - FAILS))
echo "${passed}/${total} checks passed."

if [ "$FAILS" -eq 0 ]; then
    echo "RESULT: ALL PASS"
    exit 0
else
    echo "RESULT: FAIL ($FAILS check(s) failed)"
    exit 1
fi
