#!/usr/bin/env python3
"""Off-mode gate for support groups.

docs/superpowers/plans/2026-09-02-support-sets-and-groups.md §3.7.

TWO GATES, and the default is the tolerance one:

  --gate tolerance  (default) run each pair of G-code files through the fork's own Slice
                    Compare engine and require: zero changed config rows, zero changed layers,
                    zero layers present on only one side, and at least --segment-tolerance per
                    cent of segments matching (default 99.0).

                    The plan asked for 100 % of segments. The BASELINE CANNOT MEET THAT AGAINST
                    ITSELF: running this script with one executable on both sides still shows a
                    handful of segments (10-18 out of several thousand, on 4-7 layers of a 41-66
                    layer print) appearing or vanishing in roughly one case per run. The
                    structural criteria - config rows, changed layers, added or removed layers -
                    ARE stable at zero, so they are required exactly, and the segment count is
                    thresholded instead. A support-group regression would move layers or a large
                    fraction of segments, not 0.4 % of them; classic tree support, which really
                    does move (see below), lands at 6 %.
                    The engine is reached through tests/slice_compare_cli, a test-only
                    executable calling SliceCompare::load_snapshot_from_file and the diff_*
                    functions directly - nothing was added to the shipped application.
  --gate bytes      the original byte comparison, described below. Kept for the day the
                    determinism fix lands; it does NOT pass on this tree.
  --gate groups     the ON-mode gate, added in Stage 3. It runs ONLY the corpus cases marked
                    "groups": true - the ones whose parts actually carry support_group data -
                    and inverts the question: each one must DIFFER from the baseline, because the
                    baseline ignores the groups and the candidate honours them. It also requires
                    zero changed CONFIG rows, so the difference is provably geometry and not a
                    settings change, and where a case names "expect_tool" it requires that tool
                    change to appear in the candidate's G-code and NOT in the baseline's.

The two default gates (tolerance, bytes) SKIP the "groups": true cases, for the same reason:
from Stage 3 on those cases are meant to differ. Off mode - every project that carries no
support_group data, plus any where every part resolves to the same support config - is what the
tolerance gate covers, and it is the hard gate.

Why the default moved: the plan's own 5.1 experiment - run this script with the SAME
executable on both sides - showed that about a third of same-binary comparisons differ by a
block of roughly 40 extrusion lines. That is not support-specific (a no-support control
differs too), it survives pinning to one CPU and it survives disabling Arachne. Byte identity
is therefore not an acceptance criterion this codebase can meet today. The tolerance gate
still catches everything a support-group change could cause: any layer whose extrusion,
timing or footprint moved, and any segment that appeared, vanished or shifted.

Slices every case of tests/data/support_corpus/corpus.json with two builds of the slicer and
compares the G-code byte for byte, after normalising two things and nothing else - not the config
block, not layer counts, not a single extrusion coordinate:

  1. the `; generated by <version> on <local timestamp>` header (src/libslic3r/GCode.cpp:2275);
  2. the `id:<N>` token of the `; printing object <name> id:<N> copy <n>` comment family
     (GCode.cpp:6651, :6724, :6840, :6995 and the "unique label id:" variants).

(2) is a deviation from the plan's §3.7, which asks for one normalised line. It is forced, and the
plan's own §5.1 experiment is what forced it: running this script with the SAME executable on both
sides shows that token differing between two runs of one binary as soon as the plate holds more
than one object (`id:0` vs `id:9223578746636304929`). It is ModelObject::id(), a process-global
ObjectID counter used only to label the object-exclusion comments - a name, never geometry. Every
coordinate stays strictly compared. Cases with a single object are reproducible without it.

SINGLE CORE IS MANDATORY, and is the other thing 5.1 found. On all cores the slicer is simply
not self-reproducible when it generates support: roughly a third of runs of ONE binary on ONE
project differ from the previous run, in extrusion coordinates and sometimes in whole blocks,
and classic tree support varied by a thousand G-code lines between runs. Pinning the process to
one CPU makes TBB run a single thread (Thread.cpp:222 sizes the arena from
tbb::this_task_arena::max_concurrency(), which honours the affinity mask) and the output becomes
stable. This script therefore pins its own affinity before spawning anything and the slicer
inherits it. --all-cores turns that off, and is only useful to demonstrate the nondeterminism.

    python scripts/support_group_identity.py --baseline <old exe> --candidate <new exe> \
           --corpus tests/data/support_corpus --out <dir> [--datadir <isolated dd>]

Pass the same executable twice to run the plan's §5.1 experiment - "is the corpus reproducible at
all?" - before trusting any later comparison.

Exits non-zero on the first difference, naming the first differing line. Always pass --datadir so
the run cannot touch a real profile tree.
"""
import argparse
import ctypes
import hashlib
import json
import math
import os
import re
import shutil
import subprocess
import sys
import time

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, HERE)
from orca_cli import OrcaCli  # noqa: E402

# The one line that legitimately differs between two runs.
GENERATED_BY = "; generated by "
# ModelObject::id() in the object-exclusion labels - a process-global counter, not geometry.
OBJECT_ID = re.compile(r"(printing object.*\bid:\s*)\d+")


def pin_to_one_cpu():
    """Restrict this process, and every child it spawns, to a single CPU.

    TBB sizes its arena from the affinity mask, so the slicer then runs one worker thread and
    its output stops depending on thread scheduling. Windows only; on Linux wrap the call in
    `taskset -c 0` instead.
    """
    if not sys.platform.startswith("win"):
        print("note: single-core pinning is Windows-only here; use `taskset -c 0` on Linux",
              file=sys.stderr)
        return False
    k = ctypes.windll.kernel32
    k.GetCurrentProcess.restype = ctypes.c_void_p
    k.SetProcessAffinityMask.argtypes = [ctypes.c_void_p, ctypes.c_size_t]
    if not k.SetProcessAffinityMask(k.GetCurrentProcess(), 1):
        raise SystemExit("could not pin to one CPU; results would not be reproducible")
    return True


def normalise(path):
    """Read a .gcode, drop the generated-by header and blank the object-id labels."""
    with open(path, "r", encoding="utf-8", errors="replace", newline="") as f:
        lines = f.readlines()
    kept = [OBJECT_ID.sub(r"\1<N>", l) for l in lines if not l.startswith(GENERATED_BY)]
    h = hashlib.sha256("".join(kept).encode("utf-8", "replace")).hexdigest()
    return h, kept


def first_difference(a, b):
    """1-based line number of the first difference between two normalised line lists."""
    for i, (x, y) in enumerate(zip(a, b), start=1):
        if x != y:
            return i, x.rstrip("\r\n"), y.rstrip("\r\n")
    if len(a) != len(b):
        n = min(len(a), len(b)) + 1
        longer = a if len(a) > len(b) else b
        return n, "(end of file)" if len(a) < len(b) else longer[n - 1].rstrip("\r\n"), \
               "(end of file)" if len(b) < len(a) else longer[n - 1].rstrip("\r\n")
    return None, "", ""


DEFAULT_COMPARE_EXE = os.path.join(ROOT, "build", "tests", "slice_compare_cli", "Release",
                                   "slice_compare_cli.exe")


def compare_tolerance(compare_exe, a_path, b_path):
    """Run the Slice Compare criteria over two G-code files.

    Returns (ok, verdict dict). A non-zero exit that still produced JSON is a clean failure;
    anything else is reported as an error verdict.
    """
    # slice_compare_cli links libslic3r, which loads OpenCASCADE at run time. Its own directory
    # holds the staged DLLs; the libslic3r test target stages the same set, so add both.
    env = dict(os.environ)
    dll_dirs = [os.path.dirname(compare_exe),
                os.path.join(ROOT, "build", "tests", "libslic3r", "Release")]
    env["PATH"] = os.pathsep.join(dll_dirs + [env.get("PATH", "")])
    proc = subprocess.run([compare_exe, a_path, b_path], env=env,
                          stdout=subprocess.PIPE, stderr=subprocess.PIPE,
                          text=True, encoding="utf-8", errors="replace")
    lines = (proc.stdout or "").strip().splitlines()
    try:
        verdict = json.loads(lines[-1]) if lines else {}
    except json.JSONDecodeError:
        verdict = {}
    if not verdict:
        return False, {"ok": False,
                       "error": "slice_compare_cli produced no verdict (exit %d): %s"
                                % (proc.returncode, (proc.stderr or "")[-300:])}
    return bool(verdict.get("ok")), verdict


# Keys the CANDIDATE build has and the BASELINE build cannot: a process setting introduced by the
# branch under test. diff_configs (src/libslic3r/SliceCompare/Diff.cpp) counts a key present on one
# side only as a changed row, so without this the tolerance gate would fail EVERY case for the mere
# existence of a new setting - which says nothing about whether the slicing changed.
#
# Only a row whose BASELINE value is missing is forgiven, and only for a key on this list. A new key
# whose value differs between two builds that BOTH have it is still a changed row, and any other key
# appearing on one side only is still a changed row.
#
# 2026-09-05: the three over-support surface keys
# (docs/superpowers/specs/2026-09-05-over-support-surfaces.md). They are PrintObjectConfig members,
# so unlike support_group they do reach full_print_config and therefore the G-code CONFIG_BLOCK.
NEW_CANDIDATE_KEYS = frozenset((
    "over_support_surfaces",
    "over_support_flow",
    "over_support_speed",
))


def effective_config_rows(verdict):
    """config_rows, minus the rows that are only there because the candidate knows a new key."""
    n = verdict.get("config_rows", 0) or 0
    rows = verdict.get("changed_config")
    # slice_compare_cli caps the listing at 40 rows; if it is short, do not guess - report as is.
    if rows is None or len(rows) < n:
        return n
    return sum(1 for r in rows
               if not (r.get("key") in NEW_CANDIDATE_KEYS and not r.get("a")))


def tolerance_ok(verdict, segment_tolerance):
    """Apply the gate's criteria to a slice_compare_cli verdict.

    The tool itself only measures - it reports `ok` under the strict 100 % reading. The decision
    lives here so the threshold is visible and adjustable in one place.
    """
    if "error" in verdict:
        return False
    lay = verdict.get("layers", {})
    seg = verdict.get("segments", {})
    return (effective_config_rows(verdict) == 0 and
            lay.get("changed", 1) == 0 and
            lay.get("a_only", 1) == 0 and
            lay.get("b_only", 1) == 0 and
            float(seg.get("percent", 0.0)) >= segment_tolerance)


def has_tool_change(path, token):
    """True when the G-code contains a bare tool-change line for `token` (e.g. "T1")."""
    with open(path, "r", encoding="utf-8", errors="replace") as f:
        for line in f:
            s = line.strip()
            if s == token or s.startswith(token + " ") or s.startswith(token + ";"):
                return True
    return False


def extrusions_by_side(path, feature, axis):
    """Split one feature's extrusions into the two PARTS of a two-part fixture, per tool.

    Every corpus fixture that carries a group is one object whose parts sit apart along one axis,
    so the parts separate at the widest gap in the coordinates the feature is drawn at - read off
    the data rather than assumed, exactly as the plan's own hardware measurement did. Returns
    (split, [{tool: mm}, {tool: mm}]), the first dict for the low side.
    """
    ai = 0 if axis == "x" else 1
    tool = None
    ftype = None
    pos = [None, None]
    e_abs = True
    seg = []       # (mid coordinate on `axis`, tool, length)
    tool_re = re.compile(r"^T(\d+)\s*(;.*)?$")
    with open(path, "r", encoding="utf-8", errors="replace") as f:
        for line in f:
            t = line.strip()
            if t.startswith(";TYPE:"):
                ftype = t[6:].strip()
                continue
            m = tool_re.match(t)
            if m:
                tool = "T" + m.group(1)
                continue
            if t.startswith("M82"):
                e_abs = True
                continue
            if t.startswith("M83"):
                e_abs = False
                continue
            if not t[:3] in ("G0 ", "G1 "):
                continue
            new = list(pos)
            e = None
            for tok in t.split(";")[0].split()[1:]:
                if tok[:1] == "X":
                    new[0] = float(tok[1:])
                elif tok[:1] == "Y":
                    new[1] = float(tok[1:])
                elif tok[:1] == "E":
                    e = float(tok[1:])
            if (ftype == feature and e is not None and e > 0 and None not in pos and None not in new):
                d = math.hypot(new[0] - pos[0], new[1] - pos[1])
                if d > 0:
                    seg.append((0.5 * (pos[ai] + new[ai]), tool, d))
            pos = new
    if not seg:
        return None, [{}, {}]
    coords = sorted(s[0] for s in seg)
    gap, split = 0.0, coords[0]
    for i in range(1, len(coords)):
        g = coords[i] - coords[i - 1]
        if g > gap:
            gap, split = g, 0.5 * (coords[i] + coords[i - 1])
    sides = [{}, {}]
    for c, tl, d in seg:
        side = sides[0 if c < split else 1]
        side[tl] = side.get(tl, 0.0) + d
    return split, sides


def tool_part_shares(case, path):
    """(own-part share, other-part share, split, one-line detail) for expect_tool_part, or None.

    None when the case names no such criterion, or when the feature is missing / drawn on only
    one side of the split, in which case the assertion would be vacuous.
    """
    spec = case.get("expect_tool_part")
    if not spec:
        return None
    tool = spec["tool"]
    feature = spec.get("feature", "Support interface")
    axis = spec.get("axis", "x")
    split, sides = extrusions_by_side(path, feature, axis)
    if split is None:
        return None
    totals = [sum(s.values()) for s in sides]
    if min(totals) <= 0.0:
        return None
    shares = [sides[i].get(tool, 0.0) / totals[i] for i in (0, 1)]
    owner, other = (0, 1) if shares[0] >= shares[1] else (1, 0)
    detail = ("%s draws %.1f%% of the %s on its own part and %.1f%% of the other part's "
              "(%.1f mm of %.1f mm), split at %s=%.2f"
              % (tool, 100.0 * shares[owner], feature, 100.0 * shares[other],
                 sides[other].get(tool, 0.0), totals[other], axis, split))
    return shares[owner], shares[other], split, detail


def tool_part_ok(case, candidate_path):
    """expect_tool_part: the group's interface filament stays inside the group's own part.

    Stage 3 shipped with the geometry split right and the EXTRUDER assignment wrong: an object
    with support filament matching on handed the whole layer's "don't care" support - the base
    and the OTHER part's interface alike - to whatever extruder was first on the layer, which
    once a group had pinned its own filament was the group's (plan 2c). "A tool change exists
    somewhere in the file" cannot see that; this can. The named tool must draw at least
    `min_share` of the feature on one part and at most 1 - min_share of it on the other.
    """
    spec = case.get("expect_tool_part")
    if not spec:
        return True, ""
    tool = spec["tool"]
    feature = spec.get("feature", "Support interface")
    min_share = float(spec.get("min_share", 0.95))
    got = tool_part_shares(case, candidate_path)
    if got is None:
        return False, ("%s is missing from the candidate, or drawn on only one side of the split "
                       "- the assertion would be vacuous" % feature)
    own, other, _split, detail = got
    if own < min_share:
        return False, ("%s draws only %.1f%% of the %s on its own part (want >= %.0f%%)"
                       % (tool, 100.0 * own, feature, 100.0 * min_share))
    if other > 1.0 - min_share:
        return False, ("%s leaked onto the OTHER part (want <= %.0f%%): %s"
                       % (tool, 100.0 * (1.0 - min_share), detail))
    return True, ""


def groups_ok(verdict, case, baseline_path, candidate_path, segment_tolerance=99.0,
              baseline_has_groups=False):
    """The ON-mode criterion: the groups must ACT, and only on the geometry.

    Four requirements, in the order they are worth reading:

      1. the two G-codes must DIFFER - some layer changed, or some segments did not match. A
         baseline that ignores support_group and a candidate that honours it cannot agree;
      2. zero changed CONFIG rows. The only new key never reaches full_print_config (3.1), and no
         group value is a process setting, so the config block must be identical - which is what
         makes requirement 1 a statement about geometry rather than about settings;
      3. where the case names expect_tool, that tool change must appear in the CANDIDATE and not
         in the baseline: the group's own interface filament being scheduled, end to end;
      4. where the case names expect_tool_part, that filament must be drawn on the group's OWN
         part and essentially nowhere else - see tool_part_ok.

    --baseline-has-groups INVERTS requirement 1 and drops the second half of requirement 3.
    Requirements 1 and 3 only say anything while the baseline PREDATES the feature. Once both
    sides implement it - which is every branch cut after Stage 3 - they are unsatisfiable by
    construction, and 2c's hardware pass walked straight into that. With the flag the question
    becomes the one such a pair can actually answer: the support GEOMETRY must be UNCHANGED (the
    comparison engine reads coordinates, not tools, so it cannot see an extruder move on its own)
    and every ABSOLUTE criterion - the tool change exists; it stays on its own part - must hold in
    the candidate. That is precisely the claim of a fix that reassigns extruders and moves nothing.
    """
    if "error" in verdict:
        return False, verdict["error"]
    # Stage 4: a case may say for itself whether the baseline honours ITS kind of group. Against a
    # feat/ultra-preferences baseline the normal-support cases already act on both sides while the
    # tree cases act only in the candidate, so one command-line flag cannot describe the corpus.
    baseline_has_groups = bool(case.get("baseline_has_groups", baseline_has_groups))
    if effective_config_rows(verdict) != 0:
        return False, ("%s config row(s) changed - a group must move geometry, not settings"
                       % effective_config_rows(verdict))
    lay = verdict.get("layers", {})
    seg = verdict.get("segments", {})
    moved = (lay.get("changed", 0) or 0) > 0 or float(seg.get("percent", 100.0)) < 100.0 or \
            (lay.get("a_only", 0) or 0) > 0 or (lay.get("b_only", 0) or 0) > 0
    if baseline_has_groups:
        if not tolerance_ok(verdict, segment_tolerance):
            return False, ("the support GEOMETRY moved; with --baseline-has-groups both sides "
                           "already honour the groups, so nothing but the extruder assignment "
                           "may differ")
    elif not moved:
        return False, "identical to the baseline - the support group did NOT act"
    token = case.get("expect_tool")
    if token:
        if not has_tool_change(candidate_path, token):
            return False, "no %s tool change in the candidate - the group's interface filament was not scheduled" % token
        if not baseline_has_groups and has_tool_change(baseline_path, token):
            return False, "the baseline already has a %s tool change - the case proves nothing" % token
    ok, why = tool_part_ok(case, candidate_path)
    if not ok:
        return False, why
    # Put the before/after in the gate's own output: a number nobody has to be shown separately.
    now = tool_part_shares(case, candidate_path)
    if now is None:
        return True, ""
    note = "candidate: " + now[3]
    was = tool_part_shares(case, baseline_path)
    if was is not None:
        note += "  (baseline: %.1f%% own / %.1f%% other)" % (100.0 * was[0], 100.0 * was[1])
    return True, note


def describe(verdict):
    """One-line summary of a tolerance verdict."""
    if "error" in verdict:
        return verdict["error"]
    lay = verdict.get("layers", {})
    seg = verdict.get("segments", {})
    return ("config_rows=%s layers matched=%s identical=%s changed=%s a_only=%s b_only=%s "
            "segments=%.4f%% dirty_layers=%s"
            % (effective_config_rows(verdict), lay.get("matched"), lay.get("identical"),
               lay.get("changed"), lay.get("a_only"), lay.get("b_only"),
               seg.get("percent", 0.0), seg.get("layers_dirty")))


def slice_case(exe, datadir, case, presets, outdir, timeout, common_args):
    """Slice one corpus case; return the sorted list of .gcode files produced."""
    if os.path.isdir(outdir):
        shutil.rmtree(outdir)
    os.makedirs(outdir, exist_ok=True)
    cli = OrcaCli(exe, datadir)
    models = [os.path.join(ROOT, m) for m in case["models"]]
    for m in models:
        if not os.path.exists(m):
            raise SystemExit("corpus model missing: " + m)
    res = cli.slice(models,
                    printer=presets["printer"],
                    process=presets["process"],
                    filaments=case.get("filaments", presets["filaments"]),
                    plate=0,
                    outdir=outdir,
                    extra_args=common_args + case.get("args", []),
                    timeout=timeout)
    if res.get("return_code") != 0:
        raise SystemExit("  slice failed for %s with %s:\n    %s\n%s"
                         % (case["name"], exe, res.get("error_string", ""),
                            (res.get("stderr") or "")[-1500:]))
    return sorted(os.path.join(outdir, f) for f in os.listdir(outdir) if f.endswith(".gcode"))


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--baseline", required=True, help="path to the reference snapmaker-orca.exe")
    ap.add_argument("--candidate", required=True, help="path to the exe under test")
    ap.add_argument("--corpus", default=os.path.join(ROOT, "tests", "data", "support_corpus"))
    ap.add_argument("--out", required=True, help="scratch directory for the sliced G-code")
    ap.add_argument("--datadir", help="isolated data directory - always pass this")
    ap.add_argument("--only", action="append", default=[], help="run only these case names")
    ap.add_argument("--keep", action="store_true", help="keep the G-code of matching cases")
    ap.add_argument("--continue-on-diff", action="store_true",
                    help="report every differing case instead of stopping at the first "
                         "(useful when screening the corpus for reproducibility)")
    ap.add_argument("--timeout", type=float, default=900)
    ap.add_argument("--gate", choices=("tolerance", "bytes", "groups"), default="tolerance",
                    help="tolerance (default): the Slice Compare criteria on the off-mode cases; "
                         "bytes: the original byte comparison, which this tree cannot pass; "
                         "groups: the ON-mode gate over the cases marked \"groups\": true, which "
                         "must DIFFER - see the docstring")
    ap.add_argument("--baseline-has-groups", action="store_true",
                    help="--gate groups only: the BASELINE already implements support groups "
                         "(any pairing from Stage 3 on). Requirement 1 flips from 'must differ' "
                         "to 'the support geometry must be identical', and expect_tool no longer "
                         "has to be absent from the baseline. See groups_ok. A corpus case may "
                         "override this with its own \"baseline_has_groups\", which is how the "
                         "Stage 4 corpus keeps the normal-support and the tree group cases in one "
                         "run against one baseline.")
    ap.add_argument("--segment-tolerance", type=float, default=99.0,
                    help="minimum per cent of matching segments (default 99.0); see the "
                         "module docstring for why this is not 100")
    ap.add_argument("--compare-exe", default=DEFAULT_COMPARE_EXE,
                    help="path to slice_compare_cli (built by the slice_compare_cli target)")
    ap.add_argument("--single-core", action="store_true",
                    help="pin to one CPU. Only meaningful with --gate bytes, where it removes "
                         "some (not all) of the run-to-run variation")
    a = ap.parse_args(argv)

    for exe in (a.baseline, a.candidate):
        if not os.path.exists(exe):
            raise SystemExit("no such executable: " + exe)
    if a.gate in ("tolerance", "groups") and not os.path.exists(a.compare_exe):
        raise SystemExit("no slice_compare_cli at %s - build the slice_compare_cli target"
                         % a.compare_exe)
    if a.single_core:
        pin_to_one_cpu()
    if not a.datadir:
        print("WARNING: no --datadir; the run will use the real profile tree", file=sys.stderr)

    manifest = json.load(open(os.path.join(a.corpus, "corpus.json"), encoding="utf-8"))
    presets = manifest["presets"]
    common_args = manifest.get("common_args", [])
    cases = [c for c in manifest["cases"] if not a.only or c["name"] in a.only]
    # Cases carrying support_group data belong to exactly one of the two gates, never both:
    # from Stage 3 on the generator acts on those keys, so they must differ under --gate groups
    # and are not off-mode material for the tolerance / bytes gates.
    wanted_groups = a.gate == "groups"
    skipped = [c["name"] for c in cases if bool(c.get("groups")) != wanted_groups]
    cases = [c for c in cases if bool(c.get("groups")) == wanted_groups]
    if not cases:
        raise SystemExit("no cases selected")

    same_exe = os.path.normcase(os.path.abspath(a.baseline)) == os.path.normcase(os.path.abspath(a.candidate))
    print("baseline : %s" % a.baseline)
    print("candidate: %s%s" % (a.candidate, "   (same file - §5.1 reproducibility run)" if same_exe else ""))
    print("gate     : %s%s%s" % (a.gate,
          "" if a.gate == "bytes" else "   (segments >= %.2f%%)" % a.segment_tolerance,
          "   (pinned to one CPU)" if a.single_core else ""))
    print("corpus   : %d case(s)%s\n"
          % (len(cases), ("   (skipped %s: %s)" % ("group cases" if not wanted_groups else "off-mode cases",
                                                   ", ".join(skipped))) if skipped else ""))

    os.makedirs(a.out, exist_ok=True)
    failures = 0
    for case in cases:
        name = case["name"]
        t0 = time.time()
        sys.stdout.write("%-20s " % name)
        sys.stdout.flush()
        base_dir = os.path.join(a.out, name, "baseline")
        cand_dir = os.path.join(a.out, name, "candidate")
        base_files = slice_case(a.baseline, a.datadir, case, presets, base_dir, a.timeout, common_args)
        cand_files = slice_case(a.candidate, a.datadir, case, presets, cand_dir, a.timeout, common_args)

        if len(base_files) != len(cand_files):
            print("DIFFER  baseline produced %d gcode file(s), candidate %d"
                  % (len(base_files), len(cand_files)))
            failures += 1
            continue

        if not base_files:
            print("EMPTY   no gcode produced - the case slices nothing, fix the corpus")
            failures += 1
            continue

        bad = None
        detail = ""
        total = 0
        for bf, cf in zip(base_files, cand_files):
            if a.gate == "bytes":
                bh, bl = normalise(bf)
                ch, cl = normalise(cf)
                total += len(bl)
                if bh != ch:
                    line, x, y = first_difference(bl, cl)
                    bad = (os.path.basename(bf), "first differs at line %s" % line)
                    detail = ("          baseline : %s\n          candidate: %s"
                              % (x[:160], y[:160]))
                    break
            else:
                _strict, verdict = compare_tolerance(a.compare_exe, bf, cf)
                total += int(verdict.get("segments", {}).get("both", 0) or 0)
                if a.gate == "groups":
                    ok, why = groups_ok(verdict, case, bf, cf, a.segment_tolerance,
                                        a.baseline_has_groups)
                    mode = ("baseline acts too: geometry must MATCH"
                            if bool(case.get("baseline_has_groups", a.baseline_has_groups))
                            else "baseline is blind: geometry must DIFFER")
                    detail = "          [" + mode + "]" + chr(10) + "          " + describe(verdict)
                    if ok and why:
                        # groups_ok returns the per-part tool evidence on success; it is the
                        # whole point of the ON-mode gate, so print it next to the numbers.
                        detail += "\n          " + why
                    if not ok:
                        bad = (os.path.basename(bf), why)
                        break
                elif not tolerance_ok(verdict, a.segment_tolerance):
                    bad = (os.path.basename(bf), describe(verdict))
                    detail = "          " + json.dumps(verdict)[:600]
                    break

        if bad is None:
            unit = "lines" if a.gate == "bytes" else "segments"
            print("ok      %d file(s), %d %s, %.0fs"
                  % (len(base_files), total, unit, time.time() - t0))
            if a.gate == "groups" and detail:
                # The ON-mode gate is evidence, not just a pass: show WHAT moved.
                print(detail)
            if not a.keep and a.gate != "groups":
                shutil.rmtree(os.path.join(a.out, name), ignore_errors=True)
        else:
            f, why = bad
            print("DIFFER  %s %s" % (f, why))
            if detail:
                print(detail)
            print("          kept under %s" % os.path.join(a.out, name))
            failures += 1
            if not a.continue_on_diff:
                break  # stop on the first difference

    print()
    if failures:
        print("RESULT: %d case(s) differ" % failures)
        return 1
    print("RESULT: %s on all %d case(s)"
          % ("byte-identical" if a.gate == "bytes" else
             "the groups act" if a.gate == "groups" else "within tolerance", len(cases)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
