#!/usr/bin/env python3
"""Off-mode byte-identity gate for support groups.

docs/superpowers/plans/2026-09-02-support-sets-and-groups.md §3.7.

Slices every case of tests/data/support_corpus/corpus.json with two builds of the slicer and
compares the G-code byte for byte, after normalising two things and nothing else - not the config
block, not layer counts, not a single extrusion coordinate:

  1. the `; generated by <version> on <local timestamp>` header (src/libslic3r/GCode.cpp:2275);
  2. the `id:<N>` token of the `; printing object <name> id:<N> copy <n>` comment family
     (GCode.cpp:6651, :6724, :6840, :6995 and the "unique label id:" variants).

(2) is a deviation from the plan's §3.7, which asks for one normalised line. It is forced, and the
plan's own §5.1 experiment is what forced it: running this script with the SAME executable on both
sides shows that token differing between two runs of one binary as soon as the plate holds more
than one object (`id:0` vs `id:9223578746636304929`). It is ModelObject::id(), a process-global
ObjectID counter used only to label the object-exclusion comments - a name, never geometry. Every
coordinate stays strictly compared. Cases with a single object are reproducible without it.

SINGLE CORE IS MANDATORY, and is the other thing 5.1 found. On all cores the slicer is simply
not self-reproducible when it generates support: roughly a third of runs of ONE binary on ONE
project differ from the previous run, in extrusion coordinates and sometimes in whole blocks,
and classic tree support varied by a thousand G-code lines between runs. Pinning the process to
one CPU makes TBB run a single thread (Thread.cpp:222 sizes the arena from
tbb::this_task_arena::max_concurrency(), which honours the affinity mask) and the output becomes
stable. This script therefore pins its own affinity before spawning anything and the slicer
inherits it. --all-cores turns that off, and is only useful to demonstrate the nondeterminism.

    python scripts/support_group_identity.py --baseline <old exe> --candidate <new exe> \
           --corpus tests/data/support_corpus --out <dir> [--datadir <isolated dd>]

Pass the same executable twice to run the plan's §5.1 experiment - "is the corpus reproducible at
all?" - before trusting any later comparison.

Exits non-zero on the first difference, naming the first differing line. Always pass --datadir so
the run cannot touch a real profile tree.
"""
import argparse
import ctypes
import hashlib
import json
import os
import re
import shutil
import subprocess
import sys
import time

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, HERE)
from orca_cli import OrcaCli  # noqa: E402

# The one line that legitimately differs between two runs.
GENERATED_BY = "; generated by "
# ModelObject::id() in the object-exclusion labels - a process-global counter, not geometry.
OBJECT_ID = re.compile(r"(printing object.*\bid:\s*)\d+")


def pin_to_one_cpu():
    """Restrict this process, and every child it spawns, to a single CPU.

    TBB sizes its arena from the affinity mask, so the slicer then runs one worker thread and
    its output stops depending on thread scheduling. Windows only; on Linux wrap the call in
    `taskset -c 0` instead.
    """
    if not sys.platform.startswith("win"):
        print("note: single-core pinning is Windows-only here; use `taskset -c 0` on Linux",
              file=sys.stderr)
        return False
    k = ctypes.windll.kernel32
    k.GetCurrentProcess.restype = ctypes.c_void_p
    k.SetProcessAffinityMask.argtypes = [ctypes.c_void_p, ctypes.c_size_t]
    if not k.SetProcessAffinityMask(k.GetCurrentProcess(), 1):
        raise SystemExit("could not pin to one CPU; results would not be reproducible")
    return True


def normalise(path):
    """Read a .gcode, drop the generated-by header and blank the object-id labels."""
    with open(path, "r", encoding="utf-8", errors="replace", newline="") as f:
        lines = f.readlines()
    kept = [OBJECT_ID.sub(r"\1<N>", l) for l in lines if not l.startswith(GENERATED_BY)]
    h = hashlib.sha256("".join(kept).encode("utf-8", "replace")).hexdigest()
    return h, kept


def first_difference(a, b):
    """1-based line number of the first difference between two normalised line lists."""
    for i, (x, y) in enumerate(zip(a, b), start=1):
        if x != y:
            return i, x.rstrip("\r\n"), y.rstrip("\r\n")
    if len(a) != len(b):
        n = min(len(a), len(b)) + 1
        longer = a if len(a) > len(b) else b
        return n, "(end of file)" if len(a) < len(b) else longer[n - 1].rstrip("\r\n"), \
               "(end of file)" if len(b) < len(a) else longer[n - 1].rstrip("\r\n")
    return None, "", ""


def slice_case(exe, datadir, case, presets, outdir, timeout, common_args):
    """Slice one corpus case; return the sorted list of .gcode files produced."""
    if os.path.isdir(outdir):
        shutil.rmtree(outdir)
    os.makedirs(outdir, exist_ok=True)
    cli = OrcaCli(exe, datadir)
    models = [os.path.join(ROOT, m) for m in case["models"]]
    for m in models:
        if not os.path.exists(m):
            raise SystemExit("corpus model missing: " + m)
    res = cli.slice(models,
                    printer=presets["printer"],
                    process=presets["process"],
                    filaments=case.get("filaments", presets["filaments"]),
                    plate=0,
                    outdir=outdir,
                    extra_args=common_args + case.get("args", []),
                    timeout=timeout)
    if res.get("return_code") != 0:
        raise SystemExit("  slice failed for %s with %s:\n    %s\n%s"
                         % (case["name"], exe, res.get("error_string", ""),
                            (res.get("stderr") or "")[-1500:]))
    return sorted(os.path.join(outdir, f) for f in os.listdir(outdir) if f.endswith(".gcode"))


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--baseline", required=True, help="path to the reference snapmaker-orca.exe")
    ap.add_argument("--candidate", required=True, help="path to the exe under test")
    ap.add_argument("--corpus", default=os.path.join(ROOT, "tests", "data", "support_corpus"))
    ap.add_argument("--out", required=True, help="scratch directory for the sliced G-code")
    ap.add_argument("--datadir", help="isolated data directory - always pass this")
    ap.add_argument("--only", action="append", default=[], help="run only these case names")
    ap.add_argument("--keep", action="store_true", help="keep the G-code of matching cases")
    ap.add_argument("--continue-on-diff", action="store_true",
                    help="report every differing case instead of stopping at the first "
                         "(useful when screening the corpus for reproducibility)")
    ap.add_argument("--timeout", type=float, default=900)
    ap.add_argument("--all-cores", action="store_true",
                    help="do NOT pin to one CPU - the run will not be reproducible, see the "
                         "module docstring; only useful to demonstrate that")
    a = ap.parse_args(argv)

    for exe in (a.baseline, a.candidate):
        if not os.path.exists(exe):
            raise SystemExit("no such executable: " + exe)
    if not a.all_cores:
        pin_to_one_cpu()
    if not a.datadir:
        print("WARNING: no --datadir; the run will use the real profile tree", file=sys.stderr)

    manifest = json.load(open(os.path.join(a.corpus, "corpus.json"), encoding="utf-8"))
    presets = manifest["presets"]
    common_args = manifest.get("common_args", [])
    cases = [c for c in manifest["cases"] if not a.only or c["name"] in a.only]
    if not cases:
        raise SystemExit("no cases selected")

    same_exe = os.path.normcase(os.path.abspath(a.baseline)) == os.path.normcase(os.path.abspath(a.candidate))
    print("baseline : %s" % a.baseline)
    print("candidate: %s%s" % (a.candidate, "   (same file - §5.1 reproducibility run)" if same_exe else ""))
    print("corpus   : %d case(s)%s\n" % (len(cases),
          "" if a.all_cores else "   (pinned to one CPU)"))

    os.makedirs(a.out, exist_ok=True)
    failures = 0
    for case in cases:
        name = case["name"]
        t0 = time.time()
        sys.stdout.write("%-20s " % name)
        sys.stdout.flush()
        base_dir = os.path.join(a.out, name, "baseline")
        cand_dir = os.path.join(a.out, name, "candidate")
        base_files = slice_case(a.baseline, a.datadir, case, presets, base_dir, a.timeout, common_args)
        cand_files = slice_case(a.candidate, a.datadir, case, presets, cand_dir, a.timeout, common_args)

        if len(base_files) != len(cand_files):
            print("DIFFER  baseline produced %d gcode file(s), candidate %d"
                  % (len(base_files), len(cand_files)))
            failures += 1
            continue

        if not base_files:
            print("EMPTY   no gcode produced - the case slices nothing, fix the corpus")
            failures += 1
            continue

        bad = None
        total_lines = 0
        for bf, cf in zip(base_files, cand_files):
            bh, bl = normalise(bf)
            ch, cl = normalise(cf)
            total_lines += len(bl)
            if bh != ch:
                line, x, y = first_difference(bl, cl)
                bad = (os.path.basename(bf), line, x, y)
                break

        if bad is None:
            print("ok      %d file(s), %d lines, %.0fs" % (len(base_files), total_lines, time.time() - t0))
            if not a.keep:
                shutil.rmtree(os.path.join(a.out, name), ignore_errors=True)
        else:
            f, line, x, y = bad
            print("DIFFER  %s first differs at line %s" % (f, line))
            print("          baseline : %s" % x[:160])
            print("          candidate: %s" % y[:160])
            print("          kept under %s" % os.path.join(a.out, name))
            failures += 1
            if not a.continue_on_diff:
                break  # the plan asks to stop on the first difference

    print()
    if failures:
        print("RESULT: %d case(s) differ" % failures)
        return 1
    print("RESULT: byte-identical on all %d case(s)" % len(cases))
    return 0


if __name__ == "__main__":
    sys.exit(main())
